apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    env: dev
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template: 
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx