apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: demo-voting-app
      name: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

  