apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: worker-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

